// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'body': string;
  'card': string;
  'commentsCount': string;
  'delete': string;
  'footer': string;
  'imageUrl': string;
  'imageUrlSingl': string;
  'imageUser': string;
  'title': string;
  'update': string;
  'user': string;
  'views': string;
}
export const cssExports: CssExports;
export default cssExports;
