// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'close': string;
  'icons': string;
  'input': string;
  'root': string;
  'search': string;
}
export const cssExports: CssExports;
export default cssExports;
