// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'body': string;
  'body-text': string;
  'body-title': string;
  'card': string;
  'footer': string;
  'footer-buttons': string;
  'header': string;
  'image': string;
  'post': string;
  'user': string;
  'user-image': string;
  'user-info': string;
}
export const cssExports: CssExports;
export default cssExports;
