// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'category': string;
  'prices': string;
}
export const cssExports: CssExports;
export default cssExports;
