// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'header': string;
  'links': string;
  'links-active': string;
  'links-default': string;
  'logo': string;
  'logo-text': string;
  'navbar': string;
}
export const cssExports: CssExports;
export default cssExports;
