// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'button': string;
  'container': string;
  'description': string;
  'details': string;
  'image': string;
  'oldPrice': string;
  'price': string;
  'priceBlock': string;
  'priceGroup': string;
  'root': string;
  'title': string;
}
export const cssExports: CssExports;
export default cssExports;
