// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'body': string;
  'buttons': string;
  'footer': string;
  'header': string;
  'img': string;
  'name': string;
  'oldprice': string;
  'precent': string;
  'price': string;
  'prices': string;
  'product': string;
  'wrapper': string;
}
export const cssExports: CssExports;
export default cssExports;
