// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'content': string;
  'content-active': string;
  'modal': string;
  'modal-active': string;
  'night': string;
  'night-active': string;
}
export const cssExports: CssExports;
export default cssExports;
