// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'comentContainer': string;
  'item': string;
  'items': string;
  'root': string;
  'title': string;
  'userImage': string;
  'userInfo': string;
  'userName': string;
  'userText': string;
}
export const cssExports: CssExports;
export default cssExports;
