// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'blockForSticky': string;
  'blogs': string;
  'comments': string;
  'container': string;
  'info': string;
  'root': string;
  'sort': string;
  'tegs': string;
}
export const cssExports: CssExports;
export default cssExports;
