// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'catalog': string;
  'container': string;
  'container-info': string;
  'info': string;
  'input': string;
  'items': string;
  'search': string;
}
export const cssExports: CssExports;
export default cssExports;
