export {Product} from './Product';
export {SingelPagePost} from './SingelPagePost';
export {SingelPageProduct} from './SingelPageProduct';
export {Products} from './Products';
export {Posts} from './Posts';
export {LoginPage} from './LoginPage';
export {Home} from './Home';
export {NotfoundPage} from './NotfoundPage';
export {Basket} from './Basket';
