// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'button': string;
  'buttonRemove': string;
  'error': string;
  'img': string;
  'input': string;
  'root': string;
  'title': string;
}
export const cssExports: CssExports;
export default cssExports;
