export {paginationCalculatorPage} from './paginationCalculatorPage';
export {InputValueData} from './InoputValueDataUtils';
export {formatterRub,formatter} from './intl-Number-Format';
export {getImgForSlider} from './getImgForSlider';
export {sortArray} from './sortArrayforSelect';
export {sumDiscount} from './sumDiscount';
export {totalSum, totalSumOldPrice} from './totalSum';
export {initSelect} from './initSelect';
export {filterImageInObject} from './filterImageInObject';
export { filterTags} from './getFirstTags';
export { helperLikesFunction} from './helperLikesFunction';
export { checkUserLoginForMenu} from './loginMenuArray';
export { checkCustomValidator, checkImagesValidator, checkAddProductValidator} from './checkCustomValidator'; 
export {  validVisaCard } from './validVisaCard'; 
export {  checkResorsUpdate, findNextLevelResource } from './checkResoursUpdate'; 
export {  dateGame } from './dateForGameFormat'; 
export {  incomTotalCount } from './incomTotalCount'; 
export {  calculateResourceBarUpdate } from './calculateResourceBarUpdate'; 
export {  providesList } from './providesList'; 
export {  maxValueInObjects, checkTimeUpdate } from './checkMaxTimeForResource'; 
export {  inventoryActiveFilter } from './inventoryActiveFilter'; 
export {  dragUpdateArray } from './dragUpdateArray'; 
export {  modalActiveAccordion } from './modalActiveAccordion'; 
export {  levelCheckNextUp } from './levelCheckNextUp'; 