export {paginationCalculatorPage} from './paginationCalculatorPage';
export {categoryFilterName, selectAddProduct} from './categoryFilterName';
export {InputValueData} from './InoputValueDataUtils';
export {formatterRub,formatter} from './intl-Number-Format';
export {getImgForSlider} from './getImgForSlider';
export {sortArray,selectOptionsSort} from './sortArrayforSelect';
export {sumDiscount} from './sumDiscount';
export {totalSum, totalSumOldPrice} from './totalSum';
export {initSelect} from './initSelect';
export {filterImageInObject} from './filterImageInObject';
export { filterTags} from './getFirstTags';