// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'button': string;
  'discount': string;
  'goods': string;
  'rools': string;
  'root': string;
  'title': string;
}
export const cssExports: CssExports;
export default cssExports;
