export {ButtonGoBack} from './ButtonGoBack';
export {ButtonMain} from './ButtonMain';
export {InputMain} from './InputMain';
export {TextareaMain} from './TextareaMain';
export {CardMainPost} from './CardMainPost';
export {CustomLink} from './CustomLink';
export {FormSearch} from './FormSearch';
export {Watch} from './Watch';
export {SearchInput} from './SearchInput';