// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'current-page': string;
  'page': string;
  'pagination': string;
}
export const cssExports: CssExports;
export default cssExports;
