// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'body': string;
  'button': string;
  'container': string;
  'image': string;
  'root': string;
}
export const cssExports: CssExports;
export default cssExports;
