// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'body': string;
  'cancel': string;
  'container': string;
  'footer': string;
  'footer__buttons': string;
  'footer__date': string;
  'form': string;
  'header': string;
  'ready': string;
  'title': string;
}
export const cssExports: CssExports;
export default cssExports;
