// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'card': string;
  'container': string;
  'date': string;
  'footer': string;
  'header': string;
  'img': string;
  'info': string;
  'title': string;
}
export const cssExports: CssExports;
export default cssExports;
