// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'buttons': string;
  'count': string;
  'decrement': string;
  'delete': string;
  'img': string;
  'increment': string;
  'item': string;
  'name': string;
  'oldPrice': string;
  'price': string;
  'root': string;
  'tailPrice': string;
  'ul': string;
}
export const cssExports: CssExports;
export default cssExports;
